---
AllCops:
  Exclude:
    - .vagrant/**/*
    - vendor/**/*
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Max: 175
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Max: 7
Style/Documentation:
  Enabled: false
Style/TrivialAccessors:
  ExactNameMatch: true
